# Generated by Django 3.2.18 on 2023-03-01 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='FoodTest',
        ),
    ]
