# Generated by Django 3.2.18 on 2023-03-01 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_test_foodtest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodTest',
        ),
    ]
